# Generated by Django 2.2.4 on 2025-12-16 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='美食名称')),
                ('image', models.ImageField(upload_to='foods/', verbose_name='美食图片')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='推荐指数')),
                ('description', models.TextField(blank=True, verbose_name='美食描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '美食',
                'verbose_name_plural': '美食',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='餐厅名称')),
                ('city', models.CharField(choices=[('guangzhou', '广州'), ('shenzhen', '深圳'), ('foshan', '佛山'), ('dongguan', '东莞'), ('zhuhai', '珠海'), ('zhongshan', '中山'), ('jiangmen', '江门'), ('huizhou', '惠州'), ('other', '其他')], default='guangzhou', max_length=20, verbose_name='所在城市')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('image', models.ImageField(upload_to='restaurants/', verbose_name='餐厅图片')),
                ('description', models.TextField(verbose_name='餐厅介绍')),
                ('signature_dishes', models.CharField(help_text='多个菜品用逗号分隔', max_length=200, verbose_name='招牌菜')),
                ('opening_hours', models.CharField(default='10:00-22:00', max_length=100, verbose_name='营业时间')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '餐厅',
                'verbose_name_plural': '餐厅',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='美食名称')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('reason', models.TextField(verbose_name='推荐理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='推荐用户')),
            ],
            options={
                'verbose_name': '美食推荐',
                'verbose_name_plural': '美食推荐',
                'ordering': ['-created_at'],
            },
        ),
    ]
