# Generated by Django 2.2.4 on 2025-12-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='攻略标题')),
                ('content', models.TextField(verbose_name='路线详情')),
                ('days', models.IntegerField(verbose_name='建议游玩天数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
