# Generated by Django 2.2.4 on 2025-12-14 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tripPlanApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripplan',
            options={'ordering': ['-created_at'], 'verbose_name': '旅游攻略', 'verbose_name_plural': '旅游攻略'},
        ),
        migrations.AddField(
            model_name='tripplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='tripplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布用户'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
