# Generated by Django 2.2.4 on 2025-12-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanApp', '0002_auto_20251214_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tripPlans/', verbose_name='攻略图片'),
        ),
    ]
