# Generated by Django 2.2.4 on 2025-12-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanApp', '0004_alter_tripplan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TripPlanImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tripPlans/gallery/', verbose_name='图片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('trip_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tripPlanApp.TripPlan', verbose_name='旅游攻略')),
            ],
            options={
                'verbose_name': '攻略图片',
                'verbose_name_plural': '攻略图片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
