# Generated by Django 2.2.4 on 2025-12-11 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractionsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='游玩日期')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='票数')),
                ('status', models.CharField(default='paid', max_length=20, verbose_name='状态')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractionsApp.Attraction', verbose_name='预订景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
        ),
    ]
