# Generated by Django 2.2.4 on 2025-12-14 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='paid', max_length=20, verbose_name='状态'),
        ),
    ]
