# Generated by Django 2.2.4 on 2025-12-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('region', models.CharField(choices=[('yue_bei', '粤北'), ('yue_xi', '粤西'), ('yue_nan', '粤南'), ('yue_dong', '粤东'), ('gang_ao', '港澳')], max_length=20, verbose_name='所属区域')),
                ('description', models.TextField(verbose_name='景点介绍')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='门票价格')),
                ('image', models.ImageField(upload_to='attractions/', verbose_name='封面图')),
            ],
        ),
    ]
