# Generated by Django 2.2.4 on 2025-12-15 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractionsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['-created_at'], 'verbose_name': '景点', 'verbose_name_plural': '景点'},
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_type',
            field=models.CharField(choices=[('natural', '自然'), ('cultural', '人文'), ('mixed', '综合')], default='mixed', max_length=20, verbose_name='景点类型'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.CharField(choices=[('guangzhou', '广州'), ('shenzhen', '深圳'), ('foshan', '佛山'), ('dongguan', '东莞'), ('zhuhai', '珠海'), ('zhongshan', '中山'), ('jiangmen', '江门'), ('huizhou', '惠州'), ('zhaoqing', '肇庆'), ('shantou', '汕头'), ('chaozhou', '潮州'), ('other', '其他')], default='guangzhou', max_length=20, verbose_name='所属城市'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='attractions/maps/', verbose_name='地图位置图'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='opening_hours',
            field=models.CharField(default='09:00-18:00', max_length=200, verbose_name='开放时间'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attractions/gallery/', verbose_name='图片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractionsApp.Attraction', verbose_name='景点')),
            ],
            options={
                'verbose_name': '景点图片',
                'verbose_name_plural': '景点图片',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttractionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='attractionsApp.Attraction', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'unique_together': {('user', 'attraction')},
            },
        ),
    ]
