# Generated by Django 2.2.4 on 2025-12-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractionsApp', '0002_auto_20251215_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='门票免费'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.CharField(choices=[('guangzhou', '广州'), ('shenzhen', '深圳'), ('foshan', '佛山'), ('dongguan', '东莞'), ('zhuhai', '珠海'), ('zhongshan', '中山'), ('jiangmen', '江门'), ('huizhou', '惠州'), ('zhaoqing', '肇庆'), ('shantou', '汕头'), ('chaozhou', '潮州'), ('jieyang', '揭阳'), ('shanwei', '汕尾'), ('meizhou', '梅州'), ('shaoguan', '韶关'), ('qingyuan', '清远'), ('heyuan', '河源'), ('maoming', '茂名'), ('yangjiang', '阳江'), ('yunfu', '云浮'), ('zhanjiang', '湛江')], default='guangzhou', max_length=20, verbose_name='所属城市'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='门票价格'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='region',
            field=models.CharField(choices=[('yue_bei', '粤北'), ('yue_xi', '粤西'), ('yue_nan', '珠三角'), ('yue_dong', '粤东'), ('gang_ao', '港澳')], max_length=20, verbose_name='所属区域'),
        ),
    ]
